# Generated by Django 3.0.7 on 2020-06-20 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture_bit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['uploaded_at']},
        ),
    ]
