# Generated by Django 3.0.8 on 2020-07-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_bit', '0002_auto_20200623_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='thumbnail',
            field=models.ImageField(default='default.png', upload_to='thumbnail_pics'),
        ),
    ]
